name: flutter_esp32
description: A new Flutter application.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  dio:
  http:
  dartz: ^0.9.1
  edge_alerts: ^0.0.1
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_modular: ^3.3.1
  flutter_triple: ^1.2.3+1
  mobx: ^2.0.3
  flutter_mobx: ^2.0.1

dev_dependencies:
  build_runner: ^1.7.3
  flutter_modular_test: ^1.0.1
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2
  triple_test: ^0.0.6

flutter:

  uses-material-design: true

scripts:
  mobx: flutter pub run build_runner watch --delete-conflicting-outputs
